### ISSUE TITLE
[Bug]: Error Encountered while loading documents into Qdrant Vectorstore

### ISSUE THREAD

**Issue by plaban1981** [run-llama/llama_index#13090]
### Bug Description

```
client = qdrant_client.QdrantClient(location=":memory:")
#
vector_store = QdrantVectorStore(client=client, collection_name="paul_graham")
storage_context = StorageContext.from_defaults(vector_store=vector_store)

index = VectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)
```

## Error Encountered 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-11-5e2799602178>](https://localhost:8080/#) in <cell line: 3>()
      1 vector_store = QdrantVectorStore(client=client, collection_name="paul_graham")
      2 storage_context = StorageContext.from_defaults(vector_store=vector_store)
----> 3 index = VectorStoreIndex.from_documents(
      4     documents,
      5     storage_context=storage_context,

8 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/qdrant/base.py](https://localhost:8080/#) in use_old_sparse_encoder(self, collection_name)
    874         return (
    875             self._collection_exists(collection_name)
--> 876             and SPARSE_VECTOR_NAME_OLD
    877             in self.client.get_collection(collection_name).config.params.sparse_vectors
    878         )

TypeError: argument of type 'NoneType' is not iterable
```

Even the QdrantDemo Notebook throws the same error :

https://colab.research.google.com/github/run-llama/llama_index/blob/main/docs/docs/examples/vector_stores/QdrantIndexDemo.ipynb

### Version

llama-index==0.10.31

### Steps to Reproduce

```
!mkdir -p 'data/paul_graham/'
!wget 'https://raw.githubusercontent.com/run-llama/llama_index/main/docs/docs/examples/data/paul_graham/paul_graham_essay.txt' -O 'data/paul_graham/paul_graham_essay.txt'

# load documents
documents = SimpleDirectoryReader("./data/paul_graham/").load_data()

client = qdrant_client.QdrantClient(
    # you can use :memory: mode for fast and light-weight experiments,
    # it does not require to have Qdrant deployed anywhere
    # but requires qdrant-client >= 1.1.1
    location=":memory:"
    # otherwise set Qdrant instance address with:
    # url="http://<host>:<port>"
    # otherwise set Qdrant instance with host and port:
    #host="localhost",
    #port=6333
    # set API KEY for Qdrant Cloud
    # api_key="<qdrant-api-key>",
)

vector_store = QdrantVectorStore(client=client, collection_name="paul_graham")
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)

```

**Comment by logan-markewich** [comment]
This was just fixed: run `pip install -U llama-index-vector-stores-qdrant`

**Comment by plaban1981** [comment]
I have already installed llama-index-vector-stores-qdrant. But still encounter the belopw error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-49-da174c1b9914>](https://localhost:8080/#) in <cell line: 17>()
     15 vector_store = QdrantVectorStore(client=client, collection_name="test")
     16 storage_context = StorageContext.from_defaults(vector_store=vector_store)
---> 17 index = VectorStoreIndex.from_documents(
     18     documents,
     19     storage_context=storage_context,

8 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/qdrant/base.py](https://localhost:8080/#) in use_old_sparse_encoder(self, collection_name)
    874         collection_exists = self._collection_exists(collection_name)
    875         if collection_exists:
--> 876             cur_collection = self.client.get_collection(collection_name)
    877             return SPARSE_VECTOR_NAME_OLD in (
    878                 cur_collection.config.params.sparse_vectors or {}

TypeError: argument of type 'NoneType' is not iterable

**Comment by plaban1981** [comment]
@logan-markewich  issue is not resolved

**Comment by plaban1981** [comment]
> This was just fixed: run `pip install -U llama-index-vector-stores-qdrant`

@logan-markewich  isue not resolved
